language: python

python:
  - "2.6"
  - "2.7"

branches:
  only:
    - master

before_script: curl https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.4.0 bash

script: 
  - python run-tests.py 
